---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: staging
type: Opaque
# Best way to do it. It's trasform data into base64 and set it in data:
stringData:
  host: "mysql-service.mysql-n.svc.cluster.local"
  port: "3306"
  database: "db"
  username: "root"
  password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: staging
type: Opaque
stringData:
  # If not encode in base64 it's works but when aws3 client throw exception
  internal-endpoint: "http://minio-service.minio-n.svc.cluster.local:9000"
  external-endpoint: "http://media.localhost:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: staging
type: Opaque
stringData:
  internal-kafka: "kafka-service.staging.svc.cluster.local:9092"
