apiVersion: v1
kind: Namespace
metadata:
  name: minio-n
  labels:
    name: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-n
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP

    - name: console
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: minio
