apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: staging
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext-listener
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
  type: ClusterIP
