apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: staging
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: 'bitnami/kafka:latest'
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092
            - containerPort: 9093
          volumeMounts:
            - name: kafka-data
              mountPath: /opt/kafka
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
