version: "3.8"

networks:
  my-bridge:

services:

  client:
    build:
      dockerfile: ./Dockerfile
      context: ./client
    environment:
      NEXT_PUBLIC_API: http://localhost/api
      NEXT_PUBLIC_INTERNAL_API: http://nginx/api
    command:
      - /bin/bash
      - -c
      - |
        rm -f .env.local
        npm run build
        npm run start
    ports:
      - "3000:3000"
    networks:
      - my-bridge
