version: "3.8"

services:
    mysqldb:
        image: mysql:8.0.33
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
    minio:
        image: minio/minio:RELEASE.2023-04-07T05-28-58Z
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server --console-address ":9001" /data
    broker:
      image: confluentinc/cp-kafka:7.4.0
      ports:
        - "9092:9092"
        - "9101:9101"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_JMX_PORT: 9101
        KAFKA_JMX_HOSTNAME: localhost
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
        KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
        CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

