version: "3.8"

services:
    mysqldb:
        image: mysql:8.0.33
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
    minio:
        image: minio/minio:RELEASE.2023-04-07T05-28-58Z
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server --console-address ":9001" /data
    zookeeper:
        image: "bitnami/zookeeper:latest"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: "bitnami/kafka:3.4.0"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_DELETE_TOPIC_ENABLE=true
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
