version: "3.8"

services:
    mysqldb:
        image: mysql:8.0.33
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
