version: "3.8"

networks:
  my-bridge:
    driver: bridge

services:

  backend:
    build:
      dockerfile: ./Dockerfile
    container_name: music-service
    environment:
      DB_HOST: host.docker.internal

      MINIO_AUDIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_IMAGE_ENDPOINT: http://host.docker.internal:9000
      MINIO_SEGMENT_ENDPOINT: http://host.docker.internal:9000

      MINIO_PUBLIC_AUDIO_ENDPOINT: http://localhost/media/audio
      MINIO_PUBLIC_IMAGE_ENDPOINT: http://localhost/media/image
      MINIO_PUBLIC_SEGMENT_ENDPOINT: http://localhost/media/segment

    env_file:
      - .env
    volumes:
      - ./infra/php.ini:/usr/local/etc/php/php.ini
    networks:
      - my-bridge
  
  nginx:
    image: nginx:alpine3.17
    ports:
      - 80:80
    volumes:
      - ./public/packages:/var/www/public/packages:cached
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - my-bridge

  mysqldb:
    image: mysql:8.0.33
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-bridge
    ports:
      - "3306:3306"

  minio:
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - my-bridge

  # zookeeper:
  #   image: "bitnami/zookeeper:latest"
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka:
  #   image: "bitnami/kafka:3.4.0"
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_DELETE_TOPIC_ENABLE=true
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
      # - zookeeper
